version: '2'
services:
  dynamodb:
    container_name: dynamodb-local
    image: modli/dynamodb
    expose:
      - "8000"
  init:
    image: node:8
    container_name: init-local
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - ./db:/db
      - ./shared:/shared
    links:
      - dynamodb
    working_dir: /db
    command: /bin/bash init.sh
  documentize:
    image: node:8
    container_name: documentize
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - ./documentize:/doc
      - ./shared:/shared
    links:
      - dynamodb
    working_dir: /doc
    command: /bin/bash run.sh
