version: '2'
services:
  dynamodb:
    container_name: dynamodb-local
    image: modli/dynamodb
    expose:
      - "8000"
  init: #docker-compose run --rm init
    image: node:8
    container_name: init-local
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - ./db:/db
      - ./shared:/shared
    links:
      - dynamodb
    working_dir: /db
    command: /bin/bash run.sh
  documentize: #docker-compose run --rm documentize
    image: node:8
    container_name: documentize
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - ./documentize:/documentize
      - ./shared:/shared
    links:
      - dynamodb
    working_dir: /documentize
    command: /bin/bash run.sh
  api: #docker-compose up api
    image: node:8
    ports:
      - "8080:8080"
    container_name: documentize-api
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    volumes:
      - ./api:/api
      - ./shared:/shared
    links:
      - dynamodb
    working_dir: /api
    command: /bin/bash run.sh
